version: '3.8'

services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports: 
      - 5173:5173
    environment:
      - STUDY_NOTION_FRONTEND_SITE = http://localhost:8000

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild

        - path: ./frontend
          target: /app
          action: sync

  api:
    depends_on:
      - db
    build: ./backend

    ports: 
      - 8000:8000

    environment: 
      DB_URL: mongodb+srv://dhruvatechxr:evWUlF1kAym2mybk@cluster0.rvnfcqc.mongodb.net
    
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild

        - path: ./backend
          target: /app
          action: sync

  db:
    image: mongo:latest

    ports:
      - 27017:27017

    volumes:
      - anime:/data/db

volumes:
  anime:

  